# Generated by Django 3.0.2 on 2020-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='REG',
            fields=[
                ('usermob', models.IntegerField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=10)),
                ('Lname', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
