# Generated by Django 3.0.2 on 2020-02-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='pwd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reg',
            name='usermob',
            field=models.IntegerField(),
        ),
    ]
